// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SemanticSugar/rightsizer/clients (interfaces: CloudwatchClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/cloudwatch.go . CloudwatchClient
//

// Package mock_clients is a generated GoMock package.
package mock_clients

import (
	context "context"
	reflect "reflect"

	clients "github.com/SemanticSugar/rightsizer/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockCloudwatchClient is a mock of CloudwatchClient interface.
type MockCloudwatchClient struct {
	ctrl     *gomock.Controller
	recorder *MockCloudwatchClientMockRecorder
	isgomock struct{}
}

// MockCloudwatchClientMockRecorder is the mock recorder for MockCloudwatchClient.
type MockCloudwatchClientMockRecorder struct {
	mock *MockCloudwatchClient
}

// NewMockCloudwatchClient creates a new mock instance.
func NewMockCloudwatchClient(ctrl *gomock.Controller) *MockCloudwatchClient {
	mock := &MockCloudwatchClient{ctrl: ctrl}
	mock.recorder = &MockCloudwatchClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudwatchClient) EXPECT() *MockCloudwatchClientMockRecorder {
	return m.recorder
}

// GetAverage mocks base method.
func (m *MockCloudwatchClient) GetAverage(ctx context.Context, input *clients.GetAverageInput) (*float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverage", ctx, input)
	ret0, _ := ret[0].(*float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAverage indicates an expected call of GetAverage.
func (mr *MockCloudwatchClientMockRecorder) GetAverage(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverage", reflect.TypeOf((*MockCloudwatchClient)(nil).GetAverage), ctx, input)
}
